"""initial schema - BE-01

Revision ID: d027f9b06bd5
Revises: 
Create Date: 2026-08-05 21:57:13.257939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd027f9b06bd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('clinical_rules',
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('condition_code', sa.String(length=20), nullable=False),
    sa.Column('stages', sa.String(length=50), nullable=True),
    sa.Column('nutrient', sa.String(length=30), nullable=False),
    sa.Column('bound', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('basis', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('guideline_ref', sa.Text(), nullable=False),
    sa.Column('guideline_grade', sa.String(length=10), nullable=True),
    sa.Column('verify_status', sa.String(length=20), nullable=False),
    sa.Column('overridden_by', sa.String(length=50), nullable=True),
    sa.Column('disabled_by_flag', sa.String(length=50), nullable=True),
    sa.Column('requires_flag', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_clinical_rules_condition_code'), 'clinical_rules', ['condition_code'], unique=False)
    op.create_table('dishes',
    sa.Column('dish_id', sa.String(length=64), nullable=False),
    sa.Column('name_vi', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('serving_g', sa.Float(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_index(op.f('ix_dishes_name_vi'), 'dishes', ['name_vi'], unique=False)
    op.create_table('drug_food_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('drug_class', sa.String(length=255), nullable=True),
    sa.Column('food_or_nutrient', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('mechanism_vi', sa.Text(), nullable=False),
    sa.Column('recommendation_vi', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('verify_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_food_interactions_drug_name'), 'drug_food_interactions', ['drug_name'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_vi', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('na_mg', sa.Float(), nullable=False),
    sa.Column('k_mg', sa.Float(), nullable=False),
    sa.Column('p_mg', sa.Float(), nullable=False),
    sa.Column('purine_mg', sa.Float(), nullable=True),
    sa.Column('purine_source_ref', sa.Text(), nullable=True),
    sa.Column('gi_index', sa.Float(), nullable=True),
    sa.Column('gi_source', sa.String(length=30), nullable=True),
    sa.Column('gi_source_ref', sa.Text(), nullable=True),
    sa.Column('contains_allergens', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_name_vi'), 'food_items', ['name_vi'], unique=False)
    op.create_table('guideline_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('condition_code', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guideline_chunks_condition_code'), 'guideline_chunks', ['condition_code'], unique=False)
    op.create_table('serving_sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('serving_g', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serving_sizes_category'), 'serving_sizes', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dish_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish_id', sa.String(length=64), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.dish_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_ingredients_dish_id'), 'dish_ingredients', ['dish_id'], unique=False)
    op.create_index(op.f('ix_dish_ingredients_food_id'), 'dish_ingredients', ['food_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('lab_values', sa.JSON(), nullable=False),
    sa.Column('activity_level', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('food_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('free_text_vi', sa.String(length=255), nullable=True),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_logs_profile_id'), 'food_logs', ['profile_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('computed_nutrition', sa.JSON(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_profile_id'), 'meal_plans', ['profile_id'], unique=False)
    op.create_table('patient_allergies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('allergen', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_allergies_profile_id'), 'patient_allergies', ['profile_id'], unique=False)
    op.create_table('patient_medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_medications_profile_id'), 'patient_medications', ['profile_id'], unique=False)
    op.create_table('meal_plan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_items_plan_id'), 'meal_plan_items', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plan_items_plan_id'), table_name='meal_plan_items')
    op.drop_table('meal_plan_items')
    op.drop_index(op.f('ix_patient_medications_profile_id'), table_name='patient_medications')
    op.drop_table('patient_medications')
    op.drop_index(op.f('ix_patient_allergies_profile_id'), table_name='patient_allergies')
    op.drop_table('patient_allergies')
    op.drop_index(op.f('ix_meal_plans_profile_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_food_logs_profile_id'), table_name='food_logs')
    op.drop_table('food_logs')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_dish_ingredients_food_id'), table_name='dish_ingredients')
    op.drop_index(op.f('ix_dish_ingredients_dish_id'), table_name='dish_ingredients')
    op.drop_table('dish_ingredients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_serving_sizes_category'), table_name='serving_sizes')
    op.drop_table('serving_sizes')
    op.drop_index(op.f('ix_guideline_chunks_condition_code'), table_name='guideline_chunks')
    op.drop_table('guideline_chunks')
    op.drop_index(op.f('ix_food_items_name_vi'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_drug_food_interactions_drug_name'), table_name='drug_food_interactions')
    op.drop_table('drug_food_interactions')
    op.drop_index(op.f('ix_dishes_name_vi'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_clinical_rules_condition_code'), table_name='clinical_rules')
    op.drop_table('clinical_rules')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
