'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Icon } from '@/components/brand-artwork'
import { ApiError, createApiClient, type DaySummary, type FoodLog, type Verdict } from '@/lib/api'
import { getToken } from '@/lib/auth'

const SLOTS=[['breakfast','Bữa sáng'],['lunch','Bữa trưa'],['snack','Bữa phụ'],['dinner','Bữa tối']] as const
const VERDICT:Record<Verdict,{label:string;tone:string}>={exceeded:{label:'Cần chú ý',tone:'bg-[#c96b55]'},below_min:{label:'Nên bổ sung',tone:'bg-[#d7a33f]'},within:{label:'Đang phù hợp',tone:'bg-[#4f927c]'},insufficient_data:{label:'Cần ghi thêm',tone:'bg-[#aab8bb]'}}
type DayEntry={iso:string;summary:DaySummary|null}
function todayISO(){return new Date().toISOString().slice(0,10)}
function shiftDate(iso:string,delta:number){const d=new Date(`${iso}T00:00:00`);d.setDate(d.getDate()+delta);return d.toISOString().slice(0,10)}
function shortDate(iso:string){return new Date(`${iso}T00:00:00`).toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit'})}
function nutrient(value:number|null,unit:string|null){if(value==null)return 'Chưa tính được';return `${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:unit==='kcal'||unit==='mg'?0:1}).format(value)}${unit?` ${unit}`:''}`}

export default function DiaryPage(){
 const [profileId,setProfileId]=useState(''),[day,setDay]=useState(todayISO()),[week,setWeek]=useState<DayEntry[]>([]),[logs,setLogs]=useState<FoodLog[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const refresh=useCallback(async(pid:string,anchor:string)=>{const token=getToken();if(!token)return;const api=createApiClient(token);const dates=Array.from({length:7},(_,i)=>shiftDate(anchor,i-6));const [summaries,dayLogs]=await Promise.all([Promise.all(dates.map(async iso=>({iso,summary:await api.getDaySummary(pid,iso).catch(()=>null)}))),api.listFoodLogs(pid,anchor)]);setWeek(summaries);setLogs(dayLogs)},[])
 useEffect(()=>{const token=getToken();if(!token)return;createApiClient(token).getMyProfile().then(p=>setProfileId(p.id)).catch(v=>setError(v instanceof ApiError?v.message:'Không thể tải hồ sơ.'))},[])
 useEffect(()=>{if(!profileId)return;const timer=window.setTimeout(()=>{setLoading(true);setError('');refresh(profileId,day).catch(v=>setError(v instanceof ApiError?v.message:'Không thể tải tiến trình dinh dưỡng.')).finally(()=>setLoading(false))},0);return()=>window.clearTimeout(timer)},[profileId,day,refresh])
 const summary=week.find(e=>e.iso===day)?.summary??null
 const days=week.filter(e=>e.summary&&(e.summary.matched_count+e.summary.unmatched_count)>0).length
 const all=useMemo(()=>week.flatMap(e=>e.summary?.verdicts??[]),[week]);const best=all.filter(v=>v.verdict==='within').at(-1);const focus=all.filter(v=>v.verdict==='exceeded'||v.verdict==='below_min').at(-1);const coverage=summary?Math.round(summary.coverage*100):0
 return <div className="min-h-screen px-[38px] pb-12 pt-[34px] text-[var(--c-ink)] max-[680px]:px-[15px] max-[680px]:pb-[30px] max-[680px]:pt-[72px]">
  <header className="flex items-end justify-between gap-5 max-[720px]:grid"><div><small className="text-xs font-bold tracking-[.08em] text-[var(--c-green2)]">THEO DÕI THÓI QUEN ĂN UỐNG</small><h1 className="mt-1.5 font-[family-name:var(--f-serif)] text-[clamp(30px,4vw,38px)] font-semibold leading-[1.15]">Tiến trình dinh dưỡng</h1><p className="mt-1.5 text-base text-[var(--c-muted)]">Những thay đổi đáng chú ý từ các bữa ăn bạn đã ghi lại.</p></div><label className="grid w-fit gap-1.5 text-sm font-semibold">Ngày đang xem<input className="h-11 rounded-[9px] border border-[#cad5d8] bg-white px-3 text-base" type="date" value={day} max={todayISO()} onChange={e=>setDay(e.target.value)}/></label></header>
  {error&&<div className="mt-4 flex gap-2 rounded-xl border border-[#efb4a4] bg-[#fff5f1] p-3 text-sm text-[#8b3d2b]" role="alert"><Icon name="warning" className="w-[18px]"/>{error}</div>}
  {loading?<div className="mt-5 h-[390px] animate-pulse rounded-2xl bg-[#e7eeef]"/>:<>
   <section className="mt-5 overflow-hidden rounded-[22px] border border-[#cfe0df] bg-[linear-gradient(125deg,#f7fbfa,#edf7f5_62%,#e5f1f5)] p-6 max-[680px]:p-5"><div className="grid grid-cols-[1fr_auto] items-center gap-8 max-[680px]:grid-cols-1"><div><span className="inline-flex rounded-full bg-white/80 px-3 py-1.5 text-xs font-semibold text-[var(--c-green2)] shadow-sm">7 ngày gần nhất</span><h2 className="mt-4 font-[family-name:var(--f-serif)] text-[clamp(24px,3vw,32px)] font-semibold">Bạn đã ghi bữa trong {days}/7 ngày</h2><p className="mt-2 max-w-[58ch] text-base leading-[1.6] text-[var(--c-muted)]">{days>=5?'Bạn đang duy trì khá đều. Dữ liệu này đã giúp bạn nhìn thấy những xu hướng đầu tiên.':'Hãy ghi thêm vài bữa trong tuần để hệ thống hiểu thói quen của bạn rõ hơn.'}</p></div><div className="grid h-28 w-28 place-items-center rounded-full bg-white shadow-[0_12px_35px_rgba(38,102,98,.12)]"><div className="text-center"><strong className="block text-3xl font-semibold text-[var(--c-green2)]">{days}</strong><span className="text-sm text-[var(--c-muted)]">trên 7 ngày</span></div></div></div></section>
   <section className="mt-3.5 grid grid-cols-3 gap-3.5 max-[980px]:grid-cols-1" aria-label="Điểm nổi bật trong tuần"><Insight icon="check" eyebrow="BẠN ĐANG DUY TRÌ TỐT" title={best?.label_vi??'Thói quen ghi bữa'} body={best?'Chỉ số này đang ở mức phù hợp trong ngày bạn đã ghi.':'Mỗi bữa được ghi lại đều giúp việc theo dõi chính xác hơn.'} tone="good"/><Insight icon="info" eyebrow="ĐIỀU NÊN ĐỂ Ý" title={focus?.label_vi??'Chưa có xu hướng rõ'} body={focus?(focus.verdict==='below_min'?'Lượng ghi nhận đang thấp hơn mức được khuyến nghị.':'Lượng ghi nhận có lúc cao hơn mức được khuyến nghị.'):'Hãy tiếp tục ghi bữa để nhận gợi ý phù hợp hơn.'} tone="watch"/><Insight icon="arrowRight" eyebrow="BƯỚC NHỎ TIẾP THEO" title={focus?.verdict==='below_min'?`Bổ sung thêm ${focus.label_vi.toLowerCase()}`:'Ghi lại bữa tiếp theo'} body={focus?.verdict==='below_min'?'Thử điều chỉnh một phần nhỏ trong bữa tiếp theo, không cần thay đổi mọi thứ cùng lúc.':'Chỉ mất ít phút và không cần ghi thật hoàn hảo.'} tone="action"/></section>
   <div className="mt-3.5 grid grid-cols-[minmax(0,1.3fr)_minmax(290px,.7fr)] gap-3.5 max-[980px]:grid-cols-1"><section className="rounded-2xl border border-[#d8e1e3] bg-white p-5 shadow-[0_9px_28px_rgba(27,83,81,.045)]"><div className="flex items-center justify-between gap-3"><div><small className="text-xs font-bold tracking-[.08em] text-[var(--c-green2)]">NGÀY {shortDate(day)}</small><h2 className="mt-1 text-2xl font-semibold">Các bữa bạn đã ghi</h2></div><span className="rounded-full bg-[#e3f0f4] px-3 py-1.5 text-xs font-semibold text-[var(--c-green2)]">{logs.length} món</span></div>{logs.length?<div className="mt-3">{logs.map(log=><LogRow key={log.id} log={log}/>)}</div>:<div className="grid min-h-[210px] place-items-center content-center text-center"><Icon name="diary" className="w-[42px] rounded-2xl bg-[#e3f0f4] p-2.5 text-[var(--c-green2)]"/><h3 className="mt-2.5 text-lg font-semibold">Chưa có bữa nào được ghi</h3><p className="mt-1 text-sm text-[var(--c-muted)]">Bạn có thể thêm món ở trang Tuần của tôi.</p></div>}</section>
    <aside><section className="rounded-2xl border border-[#d8e1e3] bg-white p-5 shadow-[0_9px_28px_rgba(27,83,81,.045)]"><small className="text-xs font-bold tracking-[.08em] text-[var(--c-green2)]">MỨC ĐỘ GHI NHẬN</small><div className="mt-2 flex items-end justify-between gap-3"><h2 className="text-xl font-semibold">Bạn đã ghi đủ để xem chưa?</h2><strong className="text-xl tabular-nums text-[var(--c-green2)]">{coverage}%</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#e5edef]"><i className="block h-full rounded-full bg-[var(--c-green)] transition-[width] duration-500" style={{width:`${coverage}%`}}/></div><p className="mt-3 text-sm leading-[1.6] text-[var(--c-muted)]">{summary?.is_complete?'Các món trong ngày đã có đủ thông tin để xem tổng quan.':'Một vài món vẫn đang được cập nhật. Hãy ghi thêm để kết quả rõ hơn.'}</p><Link className="mt-4 flex min-h-11 items-center justify-between rounded-xl bg-[var(--c-green2)] px-4 text-sm font-semibold text-white" href="/patient/weekly">Ghi thêm món<Icon name="arrowRight" className="w-4"/></Link></section></aside></div>
   <details className="mt-3.5 rounded-2xl border border-[#d8e1e3] bg-white shadow-[0_9px_28px_rgba(27,83,81,.045)]"><summary className="flex min-h-[72px] cursor-pointer list-none items-center justify-between gap-4 px-5"><div><small className="text-xs font-bold tracking-[.08em] text-[var(--c-green2)]">DÀNH CHO NGƯỜI MUỐN XEM KỸ</small><h2 className="mt-1 text-lg font-semibold">Chi tiết dinh dưỡng ngày {shortDate(day)}</h2></div><span className="text-sm font-semibold text-[var(--c-green2)]">Mở chi tiết</span></summary><div className="grid grid-cols-2 gap-x-6 border-t border-[#e3e9ea] px-5 py-3 max-[720px]:grid-cols-1">{summary?.verdicts.length?summary.verdicts.map(item=><article key={item.nutrient} className="grid min-h-[68px] grid-cols-[7px_1fr_auto] items-center gap-3 border-b border-[#edf1f2]"><span className={`h-8 w-[6px] rounded-full ${VERDICT[item.verdict].tone}`}/><div><strong className="text-sm font-semibold">{item.label_vi}</strong><small className="mt-1 block text-xs text-[var(--c-muted)]">{nutrient(item.counted,item.unit)}</small></div><span className="text-xs font-semibold">{VERDICT[item.verdict].label}</span></article>):<p className="col-span-full py-8 text-center text-sm text-[var(--c-muted)]">Cần ghi thêm món để xem chi tiết dinh dưỡng.</p>}</div></details>
  </>}
 </div>
}

function Insight({icon,eyebrow,title,body,tone}:{icon:'check'|'info'|'arrowRight';eyebrow:string;title:string;body:string;tone:'good'|'watch'|'action'}){const color=tone==='good'?'border-[#cfe2dc] bg-[#f7fbf9]':tone==='watch'?'border-[#eadfc8] bg-[#fffaf1]':'border-[#cedee6] bg-[#f5fafc]';return <article className={`min-h-[184px] rounded-2xl border p-5 ${color}`}><Icon name={icon} className="h-10 w-10 rounded-xl bg-white p-2.5 text-[var(--c-green2)] shadow-sm"/><small className="mt-5 block text-xs font-bold tracking-[.08em] text-[var(--c-green2)]">{eyebrow}</small><h2 className="mt-1.5 text-lg font-semibold">{title}</h2><p className="mt-1.5 text-sm leading-[1.55] text-[var(--c-muted)]">{body}</p></article>}
function LogRow({log}:{log:FoodLog}){const pending=log.match_status==='unmatched'||log.match_status==='no_data';return <article className="grid min-h-[76px] grid-cols-[38px_1fr_auto] items-center gap-3 border-b border-[#e3e9ea] last:border-0"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e4f0f4] text-[var(--c-green2)]"><Icon name={pending?'info':'check'} className="w-[18px]"/></span><div><small className="text-xs text-[var(--c-muted)]">{SLOTS.find(([v])=>v===log.slot)?.[1]||'Bữa ăn'} · {new Date(log.logged_at).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</small><strong className="mt-1 block text-base font-semibold">{log.food_name_vi||log.free_text_vi}</strong></div><div className="text-right"><b className="block text-sm font-semibold tabular-nums">{log.grams!=null?`${log.grams} g`:'Chưa có khẩu phần'}</b><small className="mt-1 block text-xs text-[var(--c-muted)]">{pending?'Đang cập nhật dinh dưỡng':'Đã cập nhật'}</small></div></article>}
